# Generated by Django 4.0.10 on 2024-09-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_link_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='times_accessed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
